version: '3'
services:
  python:
    build: ./app
    depends_on:
      - redis
    environment:
      APIKEY: ${APIKEY}
      REDIS_HOST: "redis"
      REDIS_DB: "0"
      REDIS_ANALYZE: "1"
  redis:
    image: redis:4.0.2
    volumes:
      - ./redis:/data
