version: '3'
services:
  python:
    build: ./
    environment:
      APIKEY: ${APIKEY}
      REDIS_HOST: "redis"
      REDIS_DB: "0"
  redis:
    image: redis:4.0.2
    volumes:
      - ./redis:/data
